<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer" Version="3.0.141" />
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.302" />
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <PackageReference Update="Roslynator.Analyzers" Version="4.16.0" />
    <PackageReference Update="SonarAnalyzer.CSharp" Version="10.31.0.145097" />
  </ItemGroup>

</Project>
