<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AiDev.Workflow.Infrastructure\AiDev.Workflow.Infrastructure.csproj" />
    <ProjectReference Include="..\AiDev.Workflow.Application\AiDev.Workflow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Hosting.AGUI.AspNetCore" Version="1.17.0-preview.260804.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer" Version="3.0.141" />
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.302" />
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <PackageReference Update="Roslynator.Analyzers" Version="4.16.0" />
    <PackageReference Update="SonarAnalyzer.CSharp" Version="10.31.0.145097" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e4c3808-d173-4dc7-ace2-d32c8e868716</UserSecretsId>
  </PropertyGroup>

</Project>
