"""APPROVALS.md content-hash signing (plan's "approval integrity" gap): every gate resolution
for a stage that opts in (StageSpec.sign_approval) appends a signed row recording exactly what
content was approved. A later read of "the approved spec/plan" can re-hash the current on-disk
content and compare against the latest recorded row for that stage -- a post-approval edit
(accidental or adversarial) to the approved file no longer gets silently trusted as authoritative.

verify_approval is provided for that future consumer side; nothing in this codebase calls it yet
(no stage currently re-reads another stage's already-approved artifact from disk mid-run --
approved_content already lives in in-memory GraphState for the run that approved it), but exit's
manifest finalization and any future stage that resumes a thread purely by rehydrating from disk
(intake_node's hydrate_state path) are the intended callers once built.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone

from . import repo_files
from .sandbox.provider import SandboxProvider

APPROVALS_PATH = "APPROVALS.md"

_HEADER = """# Approvals

Each row below is a content-hash-signed record of one gate approval: the exact stage, run, and
SHA-256 of the approved content at the moment a human approved it. Generated by ai-dev-workflow --
hand-editing defeats its purpose (a tampered or accidental post-approval edit to the approved file
should be caught by comparing its current hash against the row for that stage, not trusted).

| Stage | Run ID | Content SHA-256 | Timestamp (UTC) |
|---|---|---|---|
"""


@dataclass(frozen=True)
class ApprovalRecord:
    stage: str
    run_id: str
    content_sha256: str
    timestamp: str


def _hash_content(content: dict) -> str:
    canonical = json.dumps(content, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _parse_rows(raw: str) -> list[ApprovalRecord]:
    records: list[ApprovalRecord] = []
    for line in raw.splitlines():
        if not line.startswith("| ") or line.startswith("| Stage") or line.startswith("|---"):
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) != 4:
            continue
        stage, run_id, content_sha256, timestamp = parts
        records.append(ApprovalRecord(stage=stage, run_id=run_id, content_sha256=content_sha256, timestamp=timestamp))
    return records


async def record_approval(
    provider: SandboxProvider, thread_id: str, stage_key: str, run_id: str, content: dict
) -> ApprovalRecord:
    """Appends a new signed row for this approval. Does not commit -- the caller's existing
    commit_paths call (make_gate_node already commits .ai-dev-workflow/ on every approval) is
    extended by its own caller to include APPROVALS.md in the same commit."""
    existing = await repo_files.read_repo_file(provider, thread_id, APPROVALS_PATH)
    record = ApprovalRecord(
        stage=stage_key,
        run_id=run_id,
        content_sha256=_hash_content(content),
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )
    row = f"| {record.stage} | {record.run_id} | {record.content_sha256} | {record.timestamp} |\n"
    # read_repo_file strips the trailing newline, so a bare concat fuses this row onto the previous
    # row's line and _parse_rows then drops both. Guarantee a newline boundary first.
    base = existing if existing is not None else _HEADER
    if base and not base.endswith("\n"):
        base += "\n"
    new_content = base + row
    await repo_files.write_repo_file(provider, thread_id, APPROVALS_PATH, new_content)
    return record


async def latest_approval(provider: SandboxProvider, thread_id: str, stage_key: str) -> ApprovalRecord | None:
    raw = await repo_files.read_repo_file(provider, thread_id, APPROVALS_PATH)
    if raw is None:
        return None
    matching = [r for r in _parse_rows(raw) if r.stage == stage_key]
    return matching[-1] if matching else None


async def verify_approval(provider: SandboxProvider, thread_id: str, stage_key: str, content: dict) -> bool:
    """True if `content`'s hash matches the latest recorded approval row for this stage -- False
    if there's no recorded approval at all, or the current content's hash doesn't match (the
    signal a post-approval edit invalidated the approval)."""
    record = await latest_approval(provider, thread_id, stage_key)
    if record is None:
        return False
    return record.content_sha256 == _hash_content(content)
